#pragma once

// One strong override per hooked XDK D3D function (list generated by
// tools/xdk_sigmatch/gen_census_hooks.py into xdk_hooks.inc). Observers: the
// native capture layer, then the D3D census; then the original function, then
// the capture layer's after-call hook.

#include "capture.h"
#include "fable2_d3d_census.h"

#define FABLE2_XDK_HOOK(ID, NAME, SYM)                                \
  extern "C" void __imp__##SYM(PPCContext& ctx, uint8_t* base);      \
  extern "C" void SYM(PPCContext& __restrict ctx, uint8_t* base) {   \
    fable2::native::capture::OnXdkCall(ID, ctx, base);               \
    fable2::d3dcensus::OnCall(ID, NAME, ctx);                        \
    __imp__##SYM(ctx, base);                                         \
    fable2::native::capture::OnXdkReturn(ID, ctx, base);             \
  }
#include "xdk_hooks.inc"
#undef FABLE2_XDK_HOOK
