// Generated by tools/xdk_sigmatch/gen_census_hooks.py - do not edit.
#pragma once
#include <cstdint>
namespace fable2::native::capture {
constexpr uint32_t kHook_D3DDevice_SetIndices = 0;
constexpr uint32_t kHook_D3DDevice_SetStreamSource = 1;
constexpr uint32_t kHook_D3DDevice_DrawIndexedVertices = 2;
constexpr uint32_t kHook_D3DDevice_DrawVertices = 3;
constexpr uint32_t kHook_D3DDevice_BeginVertices = 4;
constexpr uint32_t kHook_D3DDevice_SetPixelShader = 5;
constexpr uint32_t kHook_D3DDevice_SetVertexShader = 6;
constexpr uint32_t kHook_D3DDevice_SetRenderState = 7;
constexpr uint32_t kHook_D3DDevice_SetViewport = 8;
constexpr uint32_t kHook_D3DDevice_SetScissorRect = 9;
constexpr uint32_t kHook_D3DDevice_SetPending_AluConstants = 10;
constexpr uint32_t kHook_D3DDevice_SetIndicescallee1 = 13;
constexpr uint32_t kHook_D3DDevice_SetRenderStatecallee1 = 14;
constexpr uint32_t kHook_D3DDevice_SetViewportcallee0 = 15;
constexpr uint32_t kHook_D3DDevice_SetScissorRectcallee1 = 16;
constexpr uint32_t kHook_D3DDevice_SetRenderStatecallee1callee1 = 17;
constexpr uint32_t kHook_D3DDevice_SetViewportcallee0callee1 = 18;
constexpr uint32_t kHook_D3DDevice_SetScissorRectcallee1callee0 = 19;
constexpr uint32_t kHook_D3DDevice_SetRenderStatecallee1callee1callee0 = 20;
constexpr uint32_t kHook_D3DDevice_SetRenderStatecallee1callee1callee2 = 21;
constexpr uint32_t kHook_D3DDevice_SetRenderStatecallee1callee1callee3 = 22;
constexpr uint32_t kHook_D3DDevice_SetViewportcallee0callee1callee1 = 24;
constexpr uint32_t kHook_D3DDevice_SetRenderStatecallee1callee1callee2callee2 = 25;
constexpr uint32_t kHook_D3DDevice_SetRenderStatecallee1callee1callee3callee1 = 26;
constexpr uint32_t kHook_D3DDevice_SetRenderStatecallee1callee1callee3callee5callee1 = 30;
constexpr uint32_t kHook_D3DDevice_SetRenderStatecallee1callee1callee4callee2callee2 = 31;
constexpr uint32_t kHook_D3DDevice_SetRenderStatecallee1callee1callee4callee2callee2callee1 = 32;
constexpr uint32_t kHook_D3DDevice_SetRenderStatecallee1callee1callee4callee2callee2callee1callee14 = 33;
constexpr uint32_t kHook_D3DDevice_SetRenderStatecallee1callee1callee4callee2callee2callee1callee20 = 34;
constexpr uint32_t kHook_D3DDevice_SetRenderStatecallee1callee1callee4callee2callee2callee1callee32 = 35;
constexpr uint32_t kHook_DrawIndx_8221C9C8 = 100;
constexpr uint32_t kHook_DrawIndx_82217EE8 = 101;
constexpr uint32_t kHook_DrawIndx_82207C30 = 102;
constexpr uint32_t kHook_DrawIndx_82B9C068 = 103;
constexpr uint32_t kHook_DrawIndx2_821EF988 = 104;
constexpr uint32_t kHook_DrawIndx2_82B928A8 = 105;
constexpr uint32_t kHook_DrawIndx2_82B98770 = 106;
constexpr uint32_t kHook_DrawIndx2_82B988C8 = 107;
constexpr uint32_t kHook_DrawIndx2_82BA29B8 = 108;
constexpr uint32_t kHook_DrawIndx2_82BA5448 = 109;
constexpr uint32_t kHook_DrawIndx2_82BA5CE8 = 110;
constexpr uint32_t kHook_SetBinSelect_82B9E848 = 112;
constexpr uint32_t kHook_IndirectBuffer_82286248 = 113;
constexpr uint32_t kHook_TileReplay_82B9ED28 = 114;
}  // namespace fable2::native::capture
