"""vs-transforms.json -> src/native/capture/vs_transform_table.inc."""
import argparse
import json
from pathlib import Path


def generate(data):
    lines = ["// Generated by tools/xdk_sigmatch/gen_transform_table.py - do not edit."]
    for vs, e in sorted(data.items(), key=lambda kv: int(kv[0], 16)):
        if "base" not in e or "base2" in e:
            continue
        layout = 0 if e["layout"] == "dot" else 1
        # deformed: the shader moves the fetched position (skinning, displacement)
        # before the transform, so the record draws it undeformed.
        deformed = 1 if e.get("deformed") else 0
        lines.append(f"FABLE2_VS_TRANSFORM({vs}ull, {e['base']}, {layout}, {e.get('pos_fetch', -1)}, {deformed})")
    return "\n".join(lines) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--json", required=True)
    ap.add_argument("--out", required=True)
    a = ap.parse_args(argv)
    Path(a.out).write_text(generate(json.loads(Path(a.json).read_text())))


if __name__ == "__main__":
    main()
