"""Generate strong-symbol census hooks for mapped XDK D3D functions.

Reads the matcher output (xdk-map.json) and the generated address->symbol
table (generated/default/fable_2_init.cpp). Skips any symbol whose original
(__imp__<symbol>) is already referenced under src/ (existing override).
"""
import argparse
import json
import re
from pathlib import Path

NEAR_MISS_SCORE = 0.85
ENTRY = re.compile(r"\{\s*0x([0-9A-Fa-f]{8}),\s*(\w+)\s*\}")


def symbol_table(init_path):
    return {int(a, 16): s for a, s in ENTRY.findall(Path(init_path).read_text())}


def existing_override(src_dir, symbol):
    needle = f"__imp__{symbol}"
    for f in sorted(Path(src_dir).rglob("*")):
        if f.suffix in (".h", ".cpp", ".inc") and f.is_file() and needle in f.read_text(errors="ignore"):
            return f
    return None


def generate(map_path, init_path, src_dir):
    entries = json.loads(Path(map_path).read_text())
    symbols = symbol_table(init_path)
    lines = ["// Generated by tools/xdk_sigmatch/gen_census_hooks.py - do not edit."]
    for i, e in enumerate(entries):
        name, target = e["name"], e.get("target")
        if target is None:
            # Near-miss: single candidate with a high similarity score.
            cands = e.get("candidates") or []
            if len(cands) == 1 and e.get("score", 0) >= NEAR_MISS_SCORE:
                target, name = cands[0], name + "?"
            else:
                continue
        sym = symbols.get(target)
        if sym is None:
            lines.append(f'// skipped {name}: no generated symbol at 0x{target:08X}')
            continue
        hit = existing_override(src_dir, sym)
        if hit is not None:
            lines.append(f'// skipped {name} ({sym}): already overridden in {hit.as_posix()}')
            continue
        lines.append(f'FABLE2_D3D_CENSUS_HOOK({i}, "{name}", {sym})')
    return "\n".join(lines) + "\n"


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--map", required=True)
    p.add_argument("--init", required=True)
    p.add_argument("--src", required=True)
    p.add_argument("--out", required=True)
    a = p.parse_args()
    Path(a.out).write_text(generate(a.map, a.init, a.src))


if __name__ == "__main__":
    main()
