"""vs-transforms.json -> src/native/capture/vs_transform_table.inc.

Per shader with a transform ("base"):
  FABLE2_VS_TRANSFORM(hash, base, layout, pos_fetch, deformed)
and, when the entry has them (frame-map section 9):
  FABLE2_VS_POS_SWIZZLE(hash, swizzle)   "pos_swizzle": "yxw1" (vfetch notation)
  FABLE2_VS_SKIN(hash, index_fetch, index_component, row0, row1, row2)
      "skin": {"index_fetch": 2, "index_component": "z", "row_fetches": [6, 7, 8]}
  FABLE2_VS_TERRAIN(hash, grid, cell, height_scale, origin, tex_offset, tex_scale,
                    patch_offset, height_fetch)
      "terrain": {"grid": "c11.xy", ..., "patch_offset": null | "c113.x", "height_fetch": 16}
      registers as register * 4 + component; -1 = no patch offset.
"""
import argparse
import json
import re
from pathlib import Path

_SWZ = {"x": 0, "y": 1, "z": 2, "w": 3, "0": 4, "1": 5, "_": 7}
_COMP = "xyzw"


def swizzle_bits(text):
    """'yxw1' -> the vfetch destination swizzle (3 bits per component, x first)."""
    if len(text) != 4 or any(c not in _SWZ for c in text):
        raise ValueError(f"bad swizzle {text!r}")
    return sum(_SWZ[c] << (3 * i) for i, c in enumerate(text))


def reg_comp(text, pair=False):
    """'c47.zw' -> 47 * 4 + 2; a pair must name two consecutive components."""
    m = re.fullmatch(r"c(\d+)\.([xyzw]{1,2})", text)
    if not m or int(m.group(1)) > 255:
        raise ValueError(f"bad register {text!r}")
    comps = [_COMP.index(c) for c in m.group(2)]
    if pair and (len(comps) != 2 or comps[1] != comps[0] + 1):
        raise ValueError(f"{text!r} is not a pair of consecutive components")
    if not pair and len(comps) != 1:
        raise ValueError(f"{text!r} names more than one component")
    return int(m.group(1)) * 4 + comps[0]


def generate(data):
    lines = ["// Generated by tools/xdk_sigmatch/gen_transform_table.py - do not edit."]
    extras = []
    for vs, e in sorted(data.items(), key=lambda kv: int(kv[0], 16)):
        if "base" not in e or "base2" in e:
            continue
        layout = 0 if e["layout"] == "dot" else 1
        # deformed: the shader moves the fetched position (skinning, displacement)
        # before the transform, so the record draws it undeformed.
        deformed = 1 if e.get("deformed") else 0
        lines.append(f"FABLE2_VS_TRANSFORM({vs}ull, {e['base']}, {layout}, {e.get('pos_fetch', -1)}, {deformed})")
        if "pos_swizzle" in e:
            extras.append(f"FABLE2_VS_POS_SWIZZLE({vs}ull, 0x{swizzle_bits(e['pos_swizzle']):X})")
        if "skin" in e:
            s = e["skin"]
            rows = s["row_fetches"]
            if len(rows) != 3:
                raise ValueError(f"{vs}: skin needs three row fetches")
            comp = _COMP.index(s["index_component"])
            extras.append(f"FABLE2_VS_SKIN({vs}ull, {s['index_fetch']}, {comp}, {rows[0]}, {rows[1]}, {rows[2]})")
        if "terrain" in e:
            t = e["terrain"]
            po = t.get("patch_offset")
            fields = [reg_comp(t["grid"], pair=True), reg_comp(t["cell"], pair=True), reg_comp(t["height_scale"]),
                      reg_comp(t["origin"], pair=True), reg_comp(t["tex_offset"], pair=True),
                      reg_comp(t["tex_scale"], pair=True), -1 if po is None else reg_comp(po),
                      int(t["height_fetch"])]
            extras.append(f"FABLE2_VS_TERRAIN({vs}ull, {', '.join(str(f) for f in fields)})")
    return "\n".join(lines + extras) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--json", required=True)
    ap.add_argument("--out", required=True)
    a = ap.parse_args(argv)
    Path(a.out).write_text(generate(json.loads(Path(a.json).read_text())))


if __name__ == "__main__":
    main()
