"""ps-albedo.json -> src/native/capture/ps_albedo_table.inc.

  FABLE2_PS_ALBEDO(hash, slot, u_interp, u_comp, u_s0, u_o0, u_s1, u_o1,
                   v_interp, v_comp, v_s0, v_o0, v_s1, v_o1)
  FABLE2_PS_NO_ALBEDO(hash)
Stage refs use uv_refs notation with bank 1 (pixel constants).
"""
import argparse
import json
from pathlib import Path

import uv_refs


def generate(data):
    lines = ["// Generated by tools/xdk_sigmatch/gen_albedo_table.py - do not edit."]
    for ps, e in sorted(data.items(), key=lambda kv: int(kv[0], 16)):
        h = f"0x{int(ps, 16):016X}ull"
        if "no_albedo" in e:
            lines.append(f"FABLE2_PS_NO_ALBEDO({h})")
            continue
        slot = int(e["slot"])
        if not 0 <= slot <= 31:
            raise ValueError(f"{ps}: bad texture fetch slot {slot}")
        fields = [str(slot)]
        for axis in ("u", "v"):
            interp, comp = uv_refs.input_comp(e[axis]["input"])
            fields += [str(interp), str(comp)] + [str(r) for r in uv_refs.stages(e[axis]["stages"], 1)]
        lines.append(f"FABLE2_PS_ALBEDO({h}, {', '.join(fields)})")
    return "\n".join(lines) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--json", required=True)
    ap.add_argument("--out", required=True)
    a = ap.parse_args(argv)
    Path(a.out).write_text(generate(json.loads(Path(a.json).read_text())))


if __name__ == "__main__":
    main()
