"""Generate strong-symbol census hooks for mapped XDK D3D functions.

Reads the matcher output (xdk-map.json) and the generated address->symbol
table (generated/default/fable_2_init.cpp). Skips any symbol whose original
(__imp__<symbol>) is already referenced under src/ (existing override).
Optional --extra: JSON list of {name, address} hooks found by other means
(e.g. pm4_emitters.py); their IDs start at EXTRA_ID_BASE.
"""
import argparse
import json
import re
from pathlib import Path

NEAR_MISS_SCORE = 0.85
EXTRA_ID_BASE = 100
ENTRY = re.compile(r"\{\s*0x([0-9A-Fa-f]{8}),\s*(\w+)\s*\}")


def symbol_table(init_path):
    return {int(a, 16): s for a, s in ENTRY.findall(Path(init_path).read_text())}


def existing_override(src_dir, symbol):
    needle = f"__imp__{symbol}"
    for f in sorted(Path(src_dir).rglob("*")):
        if f.suffix in (".h", ".cpp", ".inc") and f.is_file() and needle in f.read_text(errors="ignore"):
            return f
    return None


def _hooks(map_path, extra_path):
    """(id, name, target) for mapped functions, then the extra hooks."""
    for i, e in enumerate(json.loads(Path(map_path).read_text())):
        name, target = e["name"], e.get("target")
        if target is None:
            # Near-miss: single candidate with a high similarity score.
            cands = e.get("candidates") or []
            if len(cands) == 1 and e.get("score", 0) >= NEAR_MISS_SCORE:
                target, name = cands[0], name + "?"
            else:
                continue
        yield i, name, target
    if extra_path:
        for i, e in enumerate(json.loads(Path(extra_path).read_text())):
            yield EXTRA_ID_BASE + i, e["name"], int(e["address"], 16)


def generate(map_path, init_path, src_dir, extra_path=None):
    symbols = symbol_table(init_path)
    lines = ["// Generated by tools/xdk_sigmatch/gen_census_hooks.py - do not edit."]
    emitted = {}
    for i, name, target in _hooks(map_path, extra_path):
        sym = symbols.get(target)
        if sym is None:
            lines.append(f'// skipped {name}: no generated symbol at 0x{target:08X}')
            continue
        hit = existing_override(src_dir, sym)
        if hit is not None:
            lines.append(f'// skipped {name} ({sym}): already overridden in {hit.as_posix()}')
            continue
        if sym in emitted:
            lines.append(f'// skipped {name} ({sym}): symbol already hooked by {emitted[sym]}')
            continue
        emitted[sym] = name
        lines.append(f'FABLE2_XDK_HOOK({i}, "{name}", {sym})')
    return "\n".join(lines) + "\n"


def _sanitize(name):
    return name.replace("?", "").replace(".", "").replace(":", "_")


def generate_ids(map_path, init_path, src_dir, extra_path=None):
    """C++ header with one constexpr id per emitted hook."""
    body = generate(map_path, init_path, src_dir, extra_path)
    lines = ["// Generated by tools/xdk_sigmatch/gen_census_hooks.py - do not edit.", "#pragma once",
             "#include <cstdint>", "namespace fable2::native::capture {"]
    for m in re.finditer(r'FABLE2_XDK_HOOK\((\d+), "([^"]+)", \w+\)', body):
        lines.append(f"constexpr uint32_t kHook_{_sanitize(m.group(2))} = {m.group(1)};")
    lines.append("}  // namespace fable2::native::capture")
    return "\n".join(lines) + "\n"


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--map", required=True)
    p.add_argument("--init", required=True)
    p.add_argument("--src", required=True)
    p.add_argument("--out", required=True)
    p.add_argument("--extra", help="JSON list of {name, address} extra hooks")
    p.add_argument("--ids-out", help="also write a C++ header of kHook_<Name> ids")
    a = p.parse_args()
    Path(a.out).write_text(generate(a.map, a.init, a.src, a.extra))
    if a.ids_out:
        Path(a.ids_out).write_text(generate_ids(a.map, a.init, a.src, a.extra))


if __name__ == "__main__":
    main()
